language: python

sudo: required
dist: trusty

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"


# command to install dependencies
install:
  - sudo apt-get update
  - pip --version
  - pip install antlr4-python2-runtime
  - pip install -e .
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install antlr4-python2-runtime; else pip install antlr4-python3-runtime; fi

# command to run tests
script:
  - make check
